// src/components/layout/Footer.vue
<template>
  <footer class="relative overflow-hidden">
    <MagicCard
      ref="footerRef"
      :glow-color="'59, 130, 246'"
      :spotlight-radius="300"
      :enable-border-glow="true"
      :enable-spotlight="true"
      :disable-animations="false"
      class="relative bg-white/60 dark:bg-gray-900/60 backdrop-blur-xl text-gray-900 dark:text-white border-t border-white/30 dark:border-gray-700/30 shadow-2xl overflow-hidden"
    >
      <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        <div class="grid grid-cols-1 md:grid-cols-4 gap-8">
          <div class="col-span-1 md:col-span-2">
            <div class="flex items-center space-x-2 mb-4">
              <div class="w-8 h-8 rounded-lg overflow-hidden">
                <img src="https://file.fis.ink/img/fishcpy/logo_c.png" alt="fishcpy logo" class="w-full h-full object-cover" />
              </div>
              <span class="font-semibold text-xl">{{ personalStore.fullName }}</span>
            </div>
            <p class="text-gray-600 dark:text-gray-300 mb-4 max-w-md">
              {{ personalStore.info.bio }}
            </p>
            <div class="flex space-x-4">
              <a
                v-for="link in personalStore.socialLinks"
                :key="link.platform"
                :href="link.url"
                target="_blank"
                rel="noopener noreferrer"
                class="text-gray-500 dark:text-gray-400 hover:text-gray-900 dark:hover:text-white transition-colors"
                :aria-label="link.platform"
              >
                <component :is="getIcon(link.icon)" class="w-6 h-6" />
              </a>
            </div>
          </div>
          
          <div>
            <h3 class="text-lg font-semibold mb-4">快速导航</h3>
            <ul class="space-y-2">
              <li v-for="item in navigation" :key="item.name">
                <router-link
                  :to="item.href"
                  class="text-gray-600 dark:text-gray-300 hover:text-gray-900 dark:hover:text-white transition-colors"
                >
                  {{ item.name }}
                </router-link>
              </li>
            </ul>
          </div>
          
          <div>
            <h3 class="text-lg font-semibold mb-4">联系方式</h3>
            <ul class="space-y-2">
              <li class="flex items-center space-x-2">
                <Mail class="w-4 h-4 text-gray-500 dark:text-gray-400" />
                <a
                  :href="`mailto:${personalStore.contactEmail}`"
                  class="text-gray-600 dark:text-gray-300 hover:text-gray-900 dark:hover:text-white transition-colors"
                >
                  {{ personalStore.contactEmail }}
                </a>
              </li>

              <li class="flex items-center space-x-2">
                <MapPin class="w-4 h-4 text-gray-500 dark:text-gray-400" />
                <span class="text-gray-600 dark:text-gray-300">{{ personalStore.info.location }}</span>
              </li>
            </ul>
          </div>
        </div>
        
        <div class="border-t border-gray-300/50 dark:border-gray-800 mt-8 pt-8 flex flex-col md:flex-row justify-between items-center">
          <p class="text-gray-500 dark:text-gray-400 text-sm">
            &copy; {{ currentYear }} {{ personalStore.fullName }}. 保留所有权利。<br/>
            <a class="text-gray-600 dark:text-gray-300 hover:text-gray-900 dark:hover:text-white transition-colors" href="https://beian.miit.gov.cn" target="_blank">京ICP备2025138063号</a><br/>
            Fishcpy Home V1
          </p>
          <p class="text-gray-500 dark:text-gray-400 text-sm mt-2 md:mt-0">
            使用 Vue 3 + TypeScript 构建<br/>
            开源于<a class="text-gray-600 dark:text-gray-300 hover:text-gray-900 dark:hover:text-white transition-colors" href="https://github.com/fishcpy/homepage" target="_blank">GitHub</a><br/>
            注意是master分支
          </p>
        </div>
      </div>
    </MagicCard>
  </footer>
</template>

<script setup lang="ts">
import { computed, ref } from 'vue'
import { Mail, MapPin, Github, Linkedin, Twitter, MessageCircle } from 'lucide-vue-next'
import { usePersonalStore } from '@/stores/personal'
import MagicCard from '@/components/ui/MagicCard.vue'

const footerRef = ref<HTMLElement>()

const personalStore = usePersonalStore()

const currentYear = computed(() => new Date().getFullYear())

const navigation = [
  { name: '首页', href: '/' },
  { name: '关于我', href: '/about' },
  { name: '文章', href: '/articles' },
  { name: '项目作品', href: '/portfolio' },
  { name: '我的网站', href: '/sites' },
  { name: '赞助支持', href: '/sponsor' }
]

const iconMap = {
  github: Github,
  linkedin: Linkedin,
  twitter: Twitter,
  'message-circle': MessageCircle,
  mail: Mail,
  'map-pin': MapPin
}

const getIcon = (iconName: string) => {
  return iconMap[iconName as keyof typeof iconMap] || MessageCircle
}
</script>

// src/components/footer.tsx
import Link from "next/link";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { profile } from "@/data/profile";

export function Footer() {
  const currentYear = new Date().getFullYear();

  return (
    <footer className="border-t border-border/60 bg-muted/30">
      <div className="mx-auto grid w-full max-w-6xl gap-10 px-6 py-12 text-sm text-muted-foreground lg:grid-cols-[1.2fr_1fr_1fr] lg:gap-12 lg:px-12">
        <div className="space-y-4">
          <div className="flex items-center gap-3 text-base font-semibold text-foreground">
            <Avatar className="h-9 w-9">
              <AvatarImage src={profile.avatarUrl} alt={profile.name} />
              <AvatarFallback className="bg-muted" />
            </Avatar>
            <span>fishcpy</span>
          </div>
          <p>平时喜欢折腾点新奇的玩意，偶尔做点小网站&小项目。</p>
        </div>
        <div className="space-y-3">
          <p className="text-sm font-semibold text-foreground">快速导航</p>
          <div className="grid gap-2">
            <Link href="/" className="hover:text-foreground">首页</Link>
            <Link href="/projects" className="hover:text-foreground">项目</Link>
            <Link href="/websites" className="hover:text-foreground">网站</Link>
            <Link href="/posts" className="hover:text-foreground">文章</Link>
          </div>
        </div>
        <div className="space-y-3">
          <p className="text-sm font-semibold text-foreground">联系方式</p>
          <div className="grid gap-2">
            {profile.contact.emails.map((email) => (
              <a
                key={email}
                className="hover:text-foreground"
                href={`mailto:${email}`}
              >
                {email}
              </a>
            ))}
            <span>{profile.location}</span>
          </div>
        </div>
      </div>
      <div className="border-t border-border/60">
        <div className="mx-auto flex w-full max-w-6xl flex-col gap-3 px-6 py-6 text-xs text-muted-foreground lg:px-12">
          <div className="flex flex-wrap items-center gap-2">
            <span>
              &copy; {currentYear} {profile.footer.owner}. {profile.footer.rights}
            </span>
          </div>
          <div className="flex flex-wrap items-center justify-between gap-4 text-xs sm:flex-nowrap">
            <div className="flex flex-wrap items-center gap-4">
              {profile.footer.sponsor && (
                <a
                  className="hover:text-foreground"
                  href={profile.footer.sponsor.href}
                  target="_blank"
                  rel="noreferrer"
                >
                  赞助: {profile.footer.sponsor.label}
                </a>
              )}
              <a
                className="hover:text-foreground"
                href={profile.footer.beian.href}
                target="_blank"
                rel="noreferrer"
              >
                {profile.footer.beian.text}
              </a>
            </div>
            <span>{profile.footer.version}</span>
          </div>
        </div>
      </div>
    </footer>
  );
}
